#! /bin/bash

# Assumes that miniconda is installed, with an environment similar to the one
# the environmet  directory (note, not all packages are requirements.
# Requirements: os sys numpy scipy matplotlib srtm elevation utm ....
# missing packages can always be installed  as needed.

# The eports need to be adapted 

export CONDA_ROOT='/home/vrath/.Miniconda24/'

export FEMTIC_ENVI='FEMTIC'
export FEMTIC_ROOT=''
export FEMTIC_DATA=''

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/vrath/.Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
__conda_setup="$('${CONDA_ROOT}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f ${CONDA_ROOT}/etc/profile.d/conda.sh ]; then
        . ${CONDA_ROOT}/etc/profile.d/conda.sh
    else
        export PATH='${CONDA_ROOT}/bin:$PATH'
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

cd ${FEMTIC_ROOT}
conda activate ${FEMTIC_ENVI}
